version: '3.7'

services:
  mongo-expess:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_BASICAUTH_USERNAME: department_admin
      ME_CONFIG_BASICAUTH_PASSWORD: debian
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: department_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: debian
    expose:
      - '8081'
    links:
      - db
    networks:
      - mongo-compose-network
  db:
    image: mongo:latest
    container_name: department_mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: departments
      MONGO_INITDB_ROOT_USERNAME: department_admin
      MONGO_INITDB_ROOT_PASSWORD: debian
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge

volumes:
  mongodb_data_container: